// packages/sdk/react/examples/hello-react/src/App.tsx
import { useBoolVariation, useInitializationStatus } from '@launchdarkly/react-sdk';

import './App.css';

// Set FLAG_KEY to the feature flag key you want to evaluate.
const FLAG_KEY = import.meta.env.LAUNCHDARKLY_FLAG_KEY ?? 'sample-feature';

function App() {
  const { status } = useInitializationStatus();
  const flagValue = useBoolVariation(FLAG_KEY, false);

  let statusMessage: string;
  if (status === 'complete') {
    statusMessage = 'SDK successfully initialized!';
  } else if (status === 'failed') {
    statusMessage =
      'SDK failed to initialize. Please check your internet connection and SDK credential for any typo.';
  } else {
    statusMessage = 'Initializing\u2026';
  }

  const ready = status !== 'initializing';
  const headerBgColor = ready && flagValue ? '#00844B' : '#373841';

  return (
    <div className="App">
      <header className="App-header" style={{ backgroundColor: headerBgColor }}>
        {ready && (
          <>
            <p>{statusMessage}</p>
            <p>{`The ${FLAG_KEY} feature flag evaluates to ${flagValue}.`}</p>
          </>
        )}
      </header>
    </div>
  );
}

export default App;

// packages/sdk/vue/examples/getting-started/src/App.vue
<script setup>
import { computed } from 'vue';

import { useBoolVariation, useInitializationStatus } from '@launchdarkly/vue-client-sdk';

// Set flagKey to the feature flag key you want to evaluate.
const flagKey = import.meta.env.LAUNCHDARKLY_FLAG_KEY || 'sample-feature';

const status = useInitializationStatus();
const flagValue = useBoolVariation(flagKey, false);

const ready = computed(() => status.value.status !== 'initializing');

const statusMessage = computed(() => {
  if (status.value.status === 'complete') {
    return 'SDK successfully initialized!';
  }
  if (status.value.status === 'failed' || status.value.status === 'timeout') {
    return 'SDK failed to initialize. Please check your internet connection and SDK credential for any typo.';
  }
  return 'Initializing…';
});

// LaunchDarkly dark-mode toggle colors: off (#373841) when false, on (#00844B) when true.
const backgroundColor = computed(() => (ready.value && flagValue.value ? '#00844B' : '#373841'));
</script>

<template>
  <main class="hello" :style="{ backgroundColor }">
    <p>{{ statusMessage }}</p>
    <p v-if="ready">The {{ flagKey }} feature flag evaluates to {{ flagValue }}.</p>
  </main>
</template>

<style>
body {
  margin: 0;
}

.hello {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-family: Avenir, Helvetica, Arial, sans-serif;
  color: #ffffff;
}
</style>
